### ISSUE TITLE
error with add_annotation_from_dat.py

### ISSUE THREAD

**Issue by Wanliwill** [xuzhougeng/myscripts#3]
Hi,
When I run ：python add_annotation_from_dat.py expanded_dup.blastp.best uniprot_plants.dat
there is such an error：
Traceback (most recent call last):
  File "add_annotation_from_dat.py", line 22, in <module>
    GO_RECORD = re.findall(r"GO; (GO:\d+); ([F|P|C]):.*?; (.*):",record)
  File "/pub/anaconda3/envs/py36/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

I do not know what is wrong, please help, thank you very much

**Comment by lin0yuan** [comment]
Hi, I also got a similar error message when I run "python3 add_annotation_from_dat.py BRA1306.matches.m6.best uniprot_invertebrates.dat"

Traceback (most recent call last):
  File "add_annotation_from_dat.py", line 22, in <module>
    GO_RECORD = re.findall(r"GO; (GO:\d+); ([F|P|C]):.*?; (.*):",record)
  File "/usr/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

Would you mind giving some suggestions? Thanks a lot!

**Comment by Wanliwill** [comment]
I don't know how to solve it either, and I eventually gave up using this script.

**Comment by lin0yuan** [comment]
Hi there @Wanliwill, I successfully got rid of the error by adding a line "record = record.decode(‘utf-8’)". Maybe you can have a try.

    if not uniprot.get(acc.strip(";")):
        continue
    record = uniprot.get_raw(acc.strip(";"))

    # need to add a command here to tackle with the unicode string inconsistency between python2 and python3
    record = record.decode(‘utf-8’)

    GO_RECORD = re.findall(r"GO; (GO:\d+); ([F|P|C]):.*?; (.*):",record)

**Comment by Wanliwill** [comment]
Great. I'll give it a try. Thank you so much
